package gui;

import core.ServiceDiscovery;
import core.CustomListModel;
import core.Printer;
import java.io.IOException;
import javax.bluetooth.DiscoveryAgent;
import javax.bluetooth.LocalDevice;

/**
 * Basic application of Bluecove.
 * 
 * @author Juan-Alberto Hernández-Martínez
 */
public class MainApp extends javax.swing.JFrame {
    
    /**
     * The list model for storing and dispĺay remote devices information.
     */
    private CustomListModel listModel = new CustomListModel();
    
    /**
     * The bluetooth service discovery.
     */
    private ServiceDiscovery bluetoothServiceDiscovery;
    
    /**
     * The discovery agent.
     */
    private DiscoveryAgent agent;
    
    /**
     * Constructor for initializing the application elements.
     */
    public MainApp() {        
        initComponents();
        Printer.initMessageLabel(messageLabel);
        Printer.initStatusConsole(statusConsole);
        Printer.initModel(listModel, deviceList);        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devicePanel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        deviceScroll = new javax.swing.JScrollPane();
        deviceList = new javax.swing.JList();
        statusScroll = new javax.swing.JScrollPane();
        statusConsole = new javax.swing.JTextArea();
        optionPanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        deletePanel = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        devicePanel.setName("devicePanel"); // NOI18N
        devicePanel.setLayout(new java.awt.BorderLayout(0, 10));

        messageLabel.setName("messageLabel"); // NOI18N
        devicePanel.add(messageLabel, java.awt.BorderLayout.NORTH);

        deviceScroll.setName("deviceScroll"); // NOI18N

        deviceList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        deviceList.setName("deviceList"); // NOI18N
        deviceList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                deviceListValueChanged(evt);
            }
        });
        deviceScroll.setViewportView(deviceList);

        devicePanel.add(deviceScroll, java.awt.BorderLayout.CENTER);

        statusScroll.setName("statusScroll"); // NOI18N

        statusConsole.setEditable(false);
        statusConsole.setColumns(20);
        statusConsole.setRows(5);
        statusConsole.setName("statusConsole"); // NOI18N
        statusScroll.setViewportView(statusConsole);

        devicePanel.add(statusScroll, java.awt.BorderLayout.SOUTH);

        getContentPane().add(devicePanel, java.awt.BorderLayout.CENTER);

        optionPanel.setName("optionPanel"); // NOI18N
        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        searchButton.setText("Search");
        searchButton.setName("searchButton"); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        optionPanel.add(searchButton);

        getContentPane().add(optionPanel, java.awt.BorderLayout.NORTH);

        deletePanel.setName("deletePanel"); // NOI18N

        clearButton.setText("Clear");
        clearButton.setName("clearButton"); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        deletePanel.add(clearButton);

        getContentPane().add(deletePanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method for searching Bluetooth devices.
     * @param evt the ActionEvent
     */
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            Printer.initModel(listModel, deviceList);
            Printer.initMessage();
            Printer.setStatus("Searching for devices");            
            
            bluetoothServiceDiscovery = new ServiceDiscovery(listModel);

            LocalDevice localDevice = LocalDevice.getLocalDevice();
            
            Printer.setMessage("Local device: " + localDevice.getFriendlyName());
            
            agent = localDevice.getDiscoveryAgent();
                        
            agent.startInquiry(DiscoveryAgent.GIAC, bluetoothServiceDiscovery);

            ServiceDiscovery.initInquiry();
            ServiceDiscovery.printDevices();
        }
        catch(Exception e){
            e.getMessage();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * Method for cleaning the application's GUI.
     * @param evt the ActionEvent.
     */
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
       Printer.initMessage();
       Printer.setStatus("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * Method for selecting a specific Bluetooth device.
     * @param evt the ListSelectionEvent.
     */
    private void deviceListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_deviceListValueChanged
        try {
            int selected = deviceList.getSelectedIndex();
            
            Printer.setStatus("Selected device: " + deviceList.getSelectedValue().toString());
            
            ServiceDiscovery.setSelectedDevice(selected);
            ServiceDiscovery.checkServices(agent, bluetoothServiceDiscovery);
        }
        catch (IOException ex) {            
        }
    }//GEN-LAST:event_deviceListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JList deviceList;
    private javax.swing.JPanel devicePanel;
    private javax.swing.JScrollPane deviceScroll;
    private static javax.swing.JLabel messageLabel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextArea statusConsole;
    private javax.swing.JScrollPane statusScroll;
    // End of variables declaration//GEN-END:variables
}