package over.gui;

import java.awt.EventQueue;
import over.core.ServiceDiscovery;
import over.core.CustomListModel;
import over.core.Printer;
import java.io.IOException;
import javax.bluetooth.DiscoveryAgent;
import javax.bluetooth.LocalDevice;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * <code>BlueSD</code> class encapsulates a basic Bluecove-based client for bluetooth
 * service discovery.
 * 
 * @author Overload Inc.
 * @version 1.0, 07 Apr 2017
 */
public class BlueSD extends javax.swing.JFrame {
    
    /**
     * The list model for storing and dispĺay remote devices information.
     */
    private CustomListModel listModel = new CustomListModel();
    
    /**
     * The bluetooth service discovery.
     */
    private ServiceDiscovery bluetoothServiceDiscovery;
    
    /**
     * The discovery agent.
     */
    private DiscoveryAgent agent;
    
    /**
     * Constructor for initializing the application elements.
     */
    public BlueSD() {        
        initComponents();
        Printer.initMessageLabel(lblMessage);
        Printer.initStatusConsole(statusConsole);
        Printer.initModel(listModel, deviceList);        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devicePanel = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        deviceScroll = new javax.swing.JScrollPane();
        deviceList = new javax.swing.JList();
        statusScroll = new javax.swing.JScrollPane();
        statusConsole = new javax.swing.JTextArea();
        optionPanel = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        deletePanel = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlueSD v1.0");
        setMaximumSize(new java.awt.Dimension(270, 350));
        setName("frmBSD"); // NOI18N

        devicePanel.setMaximumSize(new java.awt.Dimension(270, 270));
        devicePanel.setMinimumSize(new java.awt.Dimension(270, 270));
        devicePanel.setName("devicePanel"); // NOI18N
        devicePanel.setPreferredSize(new java.awt.Dimension(270, 270));
        devicePanel.setLayout(new java.awt.BorderLayout(0, 10));

        lblMessage.setName("lblMessage"); // NOI18N
        devicePanel.add(lblMessage, java.awt.BorderLayout.NORTH);

        deviceScroll.setName("deviceScroll"); // NOI18N

        deviceList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        deviceList.setName("deviceList"); // NOI18N
        deviceList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                deviceListValueChanged(evt);
            }
        });
        deviceScroll.setViewportView(deviceList);

        devicePanel.add(deviceScroll, java.awt.BorderLayout.CENTER);

        statusScroll.setName("statusScroll"); // NOI18N

        statusConsole.setEditable(false);
        statusConsole.setColumns(20);
        statusConsole.setRows(5);
        statusConsole.setName("statusConsole"); // NOI18N
        statusScroll.setViewportView(statusConsole);

        devicePanel.add(statusScroll, java.awt.BorderLayout.SOUTH);

        getContentPane().add(devicePanel, java.awt.BorderLayout.CENTER);

        optionPanel.setMaximumSize(new java.awt.Dimension(270, 40));
        optionPanel.setMinimumSize(new java.awt.Dimension(270, 40));
        optionPanel.setName("optionPanel"); // NOI18N
        optionPanel.setPreferredSize(new java.awt.Dimension(270, 40));
        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        btnSearch.setText("Search");
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        optionPanel.add(btnSearch);

        getContentPane().add(optionPanel, java.awt.BorderLayout.NORTH);

        deletePanel.setMaximumSize(new java.awt.Dimension(60, 40));
        deletePanel.setMinimumSize(new java.awt.Dimension(60, 40));
        deletePanel.setName("deletePanel"); // NOI18N
        deletePanel.setPreferredSize(new java.awt.Dimension(60, 40));

        btnClear.setText("Clear");
        btnClear.setName("btnClear"); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        deletePanel.add(btnClear);

        getContentPane().add(deletePanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method for searching Bluetooth devices.
     * @param evt the ActionEvent
     */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            Printer.initModel(listModel, deviceList);
            Printer.initMessage();
            Printer.setStatus("Searching for devices");            
            
            bluetoothServiceDiscovery = new ServiceDiscovery(listModel);

            LocalDevice localDevice = LocalDevice.getLocalDevice();
            
            Printer.setMessage("Local device: " + localDevice.getFriendlyName());
            
            agent = localDevice.getDiscoveryAgent();
                        
            agent.startInquiry(DiscoveryAgent.GIAC, bluetoothServiceDiscovery);

            ServiceDiscovery.initInquiry();
            ServiceDiscovery.printDevices();
        }
        catch(IOException e){
            e.getMessage();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * Method for cleaning the application's GUI.
     * @param evt the ActionEvent.
     */
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       Printer.initMessage();
       Printer.setStatus("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * Method for selecting a specific Bluetooth device.
     * @param evt the ListSelectionEvent.
     */
    private void deviceListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_deviceListValueChanged
        try {
            int selected = deviceList.getSelectedIndex();
            
            Printer.setStatus("Selected device: " + deviceList.getSelectedValue().toString());
            
            ServiceDiscovery.setSelectedDevice(selected);
            ServiceDiscovery.checkServices(agent, bluetoothServiceDiscovery);
        }
        catch (IOException ex) {            
        }
    }//GEN-LAST:event_deviceListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());            
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlueSD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        EventQueue.invokeLater(() -> new BlueSD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JList deviceList;
    private javax.swing.JPanel devicePanel;
    private javax.swing.JScrollPane deviceScroll;
    private static javax.swing.JLabel lblMessage;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JTextArea statusConsole;
    private javax.swing.JScrollPane statusScroll;
    // End of variables declaration//GEN-END:variables
}